project:
  type: website
  output-dir: _site
  #resources:
   #- keybase.txt
   # - resume.pdf
   # - cv.pdf

metadata-files:
  - _website.yml
  - _format.yml
  - _variables.yml

execute:
  freeze: auto